### ISSUE TITLE
queryValue fails on empty response

### ISSUE THREAD

**Issue by d-oleg** [tshemsedinov/node-mysql-utilities#12]
some changes in the fillowing code will fix the problem of error on empty sql response:

 connection.queryValue = function(sql, values, callback) {
      if (typeof(values) === 'function') {
        callback = values;
        values = [];
      }
      return this.queryRow(sql, values, function(err, res, fields) {
        if (err) res = false; else res = res[Object.keys(res)[0]];
                                                   ^^^^^^ - here if queryRow returns "false" we'll get an error "Object.keys called on non-object". The following changes fixes this problem:
        if (err||!res) res = false; else res = res[Object.keys(res)[0]];
                ^^^^

**Comment by 2naive** [comment]
Is this module still supported?
Got the same problem and same solution:
`res = res ? res[Object.keys(res)[0]]: false;`
@tshemsedinov

**Comment by tshemsedinov** [comment]
@2naive do you still using mysql?
Is mysql still alive al all?

**Comment by 2naive** [comment]
Trolling as a response to issue from the maintainer is so sweet

2 фев 2017 г. 9:22 PM пользователь "Timur Shemsedinov" <
notifications@github.com> написал:

**Comment by tshemsedinov** [comment]
Frankly speaking this module is full of shit, I can merge that PR and even rewrite this code in more suitable way but I am not joking, still can't understand, why do you use mysql in 2017? @2naive

**Comment by 2naive** [comment]
Simply: If It Works, Don't Touch It
And you recommend to migrate to what? And what problems would it solve?

2 фев 2017 г. 10:18 PM пользователь "Timur Shemsedinov" <
notifications@github.com> написал:

Frankly speaking this module is full of shit, I can merge that PR and even
rewrite this code in more suitable way but I am not joking, still can't
understand, why do you use mysql in 2017? @2naive
<https://github.com/2naive>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tshemsedinov/node-mysql-utilities/issues/12#issuecomment-277054376>,
or mute the thread

**Comment by tshemsedinov** [comment]
v1.0.9 in npm
but consider move to postgres

**Comment by 2naive** [comment]
Thanks!)

2 фев 2017 г. 10:56 PM пользователь "Timur Shemsedinov" <
notifications@github.com> написал:

**Comment by tshemsedinov** [comment]
v1.0.10 in npm
